const CACHE_PREFIX='nubyx-';
const CACHE_NAME='nubyx-v0.14.5-launch-handler';
const STATIC_ASSETS=new Set(['./','./index.html','./styles.css','./future.css','./drive.css','./ai.css','./home-2050.css','./auth-2050.css','./app.js','./identity-runtime.js','./auth-revocation-guard.js','./store-session-guard.js','./store-read-session-guard.js','./store-input-guard.js','./drive-session-guard.js','./connectivity.js','./launcher.js','./session-guard.js','./sync-client.js','./sync-payload-guard.js','./sync-offline-queue.js','./sync-ui.js','./nubyx-ai.js','./logout-privacy-guard.js','./pwa-launch.js','./pwa-update.js','./manifest.webmanifest','./icon-192.svg','./icon-512.svg','./icon-512-maskable.svg']);
const REQUIRED_SHELL_ASSETS=new Set(['./index.html','./styles.css','./app.js','./identity-runtime.js','./session-guard.js','./launcher.js','./manifest.webmanifest']);
const PRIVATE_PATH_RE=/\/(api|auth|login|logout|admin|session|sessions|token|tokens|account|profile|me)(\/|$)/i;
const RUNTIME_CONFIG_RE=/\/config\.js$/i;
const SENSITIVE_QUERY_RE=/^(token|access_token|refresh_token|id_token|jwt|password|passwd|secret|client_secret|session|auth|authorization|api_key|apikey|key|code|credential|credentials|assertion|samlresponse|signature|sig)$/i;
const HTML_CONTENT_TYPE_RE=/\btext\/html\b/i;
const NON_HTML_SHELL_RE=/\.(?:js|css|webmanifest|svg)$/i;
function hasSensitiveQuery(url){for(const key of url.searchParams.keys())if(SENSITIVE_QUERY_RE.test(key))return true;return false}
function relativeKey(url){const scopePath=new URL(self.registration.scope).pathname;let path=url.pathname.startsWith(scopePath)?url.pathname.slice(scopePath.length):url.pathname;path=path.replace(/^\//,'');return path?`./${path}`:'./'}
function isWithinScope(url){const scopeUrl=new URL(self.registration.scope);return url.origin===scopeUrl.origin&&url.pathname.startsWith(scopeUrl.pathname)}
function isAuthenticatedRequest(request){return request.headers.has('authorization')||request.headers.has('cookie')}
function isPartialRequest(request){return request.headers.has('range')||request.headers.has('if-range')}
function isAllowedShellRequest(request){if(request.method!=='GET'||isAuthenticatedRequest(request)||isPartialRequest(request))return false;const url=new URL(request.url);if(!isWithinScope(url)||PRIVATE_PATH_RE.test(url.pathname)||RUNTIME_CONFIG_RE.test(url.pathname)||hasSensitiveQuery(url)||url.search)return false;return STATIC_ASSETS.has(relativeKey(url))}
function hasSafeShellMime(responseUrl,response){if(!NON_HTML_SHELL_RE.test(responseUrl.pathname))return true;return !HTML_CONTENT_TYPE_RE.test(response.headers.get('content-type')||'')}
function isCacheableResponse(response){if(!response||response.status!==200||response.type==='opaque'||response.redirected)return false;let responseUrl;try{responseUrl=new URL(response.url)}catch{return false}if(!isWithinScope(responseUrl)||PRIVATE_PATH_RE.test(responseUrl.pathname)||RUNTIME_CONFIG_RE.test(responseUrl.pathname)||hasSensitiveQuery(responseUrl)||responseUrl.search||!hasSafeShellMime(responseUrl,response))return false;const cc=(response.headers.get('cache-control')||'').toLowerCase();if(cc.includes('private')||cc.includes('no-store'))return false;if(response.headers.has('set-cookie')||response.headers.has('content-range'))return false;return true}
function isTrustedUpdateSource(source){if(!source||source.type!=='window'||!source.url)return false;try{return isWithinScope(new URL(source.url))}catch{return false}}
async function fetchShellAsset(asset){const request=new Request(asset,{credentials:'omit',cache:'no-store'});const response=await fetch(request);if(!isCacheableResponse(response))throw new Error(`uncacheable:${asset}`);return [request,response]}
async function precacheShell(){const cache=await caches.open(CACHE_NAME);const requiredFailures=[];for(const asset of STATIC_ASSETS){try{const [request,response]=await fetchShellAsset(asset);await cache.put(request,response.clone())}catch(error){if(REQUIRED_SHELL_ASSETS.has(asset))requiredFailures.push(asset)}}if(requiredFailures.length){await caches.delete(CACHE_NAME);throw new Error(`critical-shell-missing:${requiredFailures.join(',')}`)}}
async function serveShellAsset(request){const cache=await caches.open(CACHE_NAME);const cached=await cache.match(request);if(cached)return cached;const response=await fetch(request,{cache:'no-store',credentials:'omit'});if(isCacheableResponse(response))await cache.put(request,response.clone());return response}
self.addEventListener('install',event=>{event.waitUntil(precacheShell())});
self.addEventListener('message',event=>{if(event.data?.type==='NUBYX_SKIP_WAITING'&&isTrustedUpdateSource(event.source))self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith(CACHE_PREFIX)&&key!==CACHE_NAME).map(key=>caches.delete(key)));if(self.registration.navigationPreload)await self.registration.navigationPreload.enable();await self.clients.claim()})())});
self.addEventListener('fetch',event=>{const request=event.request;const url=new URL(request.url);if(request.method==='GET'&&isWithinScope(url)&&RUNTIME_CONFIG_RE.test(url.pathname)){event.respondWith(fetch(request,{cache:'no-store'}));return}if(request.mode==='navigate'){if(request.method!=='GET'||!isWithinScope(url)||PRIVATE_PATH_RE.test(url.pathname)||hasSensitiveQuery(url)||isAuthenticatedRequest(request))return;event.respondWith((async()=>{try{const preload=await event.preloadResponse;if(preload)return preload;return await fetch(request,{cache:'no-store'})}catch{return caches.open(CACHE_NAME).then(cache=>cache.match('./index.html'))}})());return}if(!isAllowedShellRequest(request))return;event.respondWith(serveShellAsset(request))});