const CACHE_PREFIX='nubyx-';
const CACHE_NAME='nubyx-v0.12.5-launcher-dedupe';
const STATIC_ASSETS=new Set(['./','./index.html','./styles.css','./future.css','./drive.css','./ai.css','./home-2050.css','./auth-2050.css','./app.js','./identity-runtime.js','./auth-revocation-guard.js','./store-session-guard.js','./store-read-session-guard.js','./store-input-guard.js','./drive-session-guard.js','./connectivity.js','./launcher.js','./session-guard.js','./sync-client.js','./sync-payload-guard.js','./sync-offline-queue.js','./sync-ui.js','./nubyx-ai.js','./logout-privacy-guard.js','./pwa-launch.js','./pwa-update.js','./manifest.webmanifest','./icon-192.svg','./icon-512.svg','./icon-512-maskable.svg']);
const PRIVATE_PATH_RE=/\/(api|auth|login|logout|admin|session|sessions|token|tokens|account|profile|me)(\/|$)/i;
const RUNTIME_CONFIG_RE=/\/config\.js$/i;
const SENSITIVE_QUERY_RE=/^(token|access_token|refresh_token|id_token|jwt|password|passwd|secret|client_secret|session|auth|authorization|api_key|apikey|key|code|credential|credentials|assertion|samlresponse|signature|sig)$/i;
function hasSensitiveQuery(url){for(const key of url.searchParams.keys())if(SENSITIVE_QUERY_RE.test(key))return true;return false}
function relativeKey(url){const scopePath=new URL(self.registration.scope).pathname;let path=url.pathname.startsWith(scopePath)?url.pathname.slice(scopePath.length):url.pathname;path=path.replace(/^\//,'');return path?`./${path}`:'./'}
function isAuthenticatedRequest(request){return request.headers.has('authorization')||request.headers.has('cookie')}
function isAllowedShellRequest(request){if(request.method!=='GET'||isAuthenticatedRequest(request))return false;const url=new URL(request.url);if(url.origin!==self.location.origin||PRIVATE_PATH_RE.test(url.pathname)||RUNTIME_CONFIG_RE.test(url.pathname)||hasSensitiveQuery(url)||url.search)return false;return STATIC_ASSETS.has(relativeKey(url))}
function isTrustedUpdateSource(source){if(!source||source.type!=='window'||!source.url)return false;try{const sourceUrl=new URL(source.url);const scopeUrl=new URL(self.registration.scope);return sourceUrl.origin===scopeUrl.origin&&sourceUrl.pathname.startsWith(scopeUrl.pathname)}catch{return false}}
async function serveShellAsset(request){const cached=await caches.match(request);if(cached)return cached;const response=await fetch(request,{cache:'no-store'});if(response.ok){const cache=await caches.open(CACHE_NAME);await cache.put(request,response.clone())}return response}
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll([...STATIC_ASSETS])))});
self.addEventListener('message',event=>{if(event.data?.type==='NUBYX_SKIP_WAITING'&&isTrustedUpdateSource(event.source))self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith(CACHE_PREFIX)&&key!==CACHE_NAME).map(key=>caches.delete(key)));if(self.registration.navigationPreload)await self.registration.navigationPreload.enable();await self.clients.claim()})())});
self.addEventListener('fetch',event=>{const request=event.request;const url=new URL(request.url);if(request.method==='GET'&&url.origin===self.location.origin&&RUNTIME_CONFIG_RE.test(url.pathname)){event.respondWith(fetch(request,{cache:'no-store'}));return}if(request.mode==='navigate'){if(request.method!=='GET'||url.origin!==self.location.origin||PRIVATE_PATH_RE.test(url.pathname)||hasSensitiveQuery(url)||isAuthenticatedRequest(request))return;event.respondWith((async()=>{try{const preload=await event.preloadResponse;if(preload)return preload;return await fetch(request,{cache:'no-store'})}catch{return caches.match('./index.html')}})());return}if(!isAllowedShellRequest(request))return;event.respondWith(serveShellAsset(request)) });